### ISSUE TITLE
nefungující odkaz na materiál o unpackingu

### ISSUE THREAD

**Issue by TECHNICKER** [spseol/PRG-No#3]
úplně dole na stránce týkající se práci s daty (https://github.com/spseol/PRG-No/blob/master/data.ipynb)

![image](https://user-images.githubusercontent.com/101834022/188488812-006f5de9-cd7e-4723-8a4d-2f4318f45a84.png)

**Comment by MarrekNozka** [comment]
opraveno 9cd1f79816833522e45d20043aa7b9ff08400626
