### ISSUE TITLE
nefunkční odkaz v důsledku chyby se závorkou

### ISSUE THREAD

**Issue by TECHNICKER** [spseol/PRG-No#4]
závorka není součástí odkazu a rozbíjí ho (https://github.com/spseol/PRG-No/blob/master/podminky.ipynb)
![image](https://user-images.githubusercontent.com/101834022/188489463-9d92cd73-747d-4f54-8152-68678653a144.png)

**Comment by MarrekNozka** [comment]
Zajímavé, že GH to sežere, ale NBviewer nee....

Opraveno 9cd1f79816833522e45d20043aa7b9ff08400626
