### ISSUE TITLE
chybějící výstup pseudo-konzole u příkladu kódu

### ISSUE THREAD

**Issue by TECHNICKER** [spseol/PRG-No#5]
možná se pletu, ale asi chybí pseudo výstup konzole u příkladů kódu(https://github.com/spseol/PRG-No/blob/master/generatory.ipynb)

![image](https://user-images.githubusercontent.com/101834022/188490816-cb5d85ef-6b40-4e0e-a44a-edd25d6b77ba.png)

![image](https://user-images.githubusercontent.com/101834022/188490835-8db78986-0865-46d2-9d2e-5f766a12b6c6.png)

**Comment by MarrekNozka** [comment]
Opraveno 9cd1f79816833522e45d20043aa7b9ff08400626
